### ISSUE TITLE
Unicode issues.

### ISSUE THREAD

**Issue by cyian-1756** [sexypants/chyoa-scraper#3]
I found that most of the stories I download end up full of things like â€, I'm assuming this is a unicode issue and could be fixed by encoding the data as uft-8 on *nix systems

**Comment by sexypants** [comment]
Can you elaborate a bit more? I've pushed commit 2dbdb61 in the mean time, if this fixes your issue, please say so. Otherwise, provide more information about your error.

**Comment by cyian-1756** [comment]
That seems to have fixed it
