### ISSUE TITLE
Add linking to story choices

### ISSUE THREAD

**Issue by cyian-1756** [sexypants/chyoa-scraper#4]
It would be nice to be able to link the choices for each chapter at the bottem of the html page

**Comment by sexypants** [comment]
Fixed in 2ffa1cf . If you only download a single chapter the HTML generator then it won't be able to determine the name of its child chapters.

It's not pretty but it gets the job done. If you'd like to make the HTML generation prettier, feel free to submit a pull request.

**Comment by cyian-1756** [comment]
I meant the chapters on disk not (The downloaded html files) not on chyoa
